### PR TITLE
feat(JSON Response): Enable JSON Response format for all Openai Calls…

### PR DESCRIPTION
**Pull request by lenaxia**
**Please describe the purpose of this pull request.**
This PR enables `response_format: {"type": "json_object"}` aka JSON mode for all openai requests. This ensures that responses are going to come back in valid JSON. While it doesn't seem to be a problem with OpenAI, using openai compatible endpoints (aka open source models) can sometimes struggle to create well formed JSON without llama.cpp's grammar restrictions. 

Also enables Debug logging by setting the env var `LOG_LEVEL: DEBUG`, case sensitive. Still defaults to false.

**How to test**

Create a file called `request.json`:
```
{
  "model": "hermes-2-pro-theta-llama3",
  "response_format": {"type": "json_object"},
  "messages": [
    {
      "content": "What is the weather in boston, seattle, and san francisco?? respond in json",
      "role": "user"
    },
    {
      "content": "{\"status\": \"OK\", \"message\": null, \"time\": \"2024-05-20 05:42:30 PM UTC+0000\"}",
      "role": "tool",
      "tool_call_id": "e394f68c-d68b-4115-97e9-989a0"
    }
  ],
  "frequency_penalty": 0,
  "logprobs": false,
  "n": 1,
  "presence_penalty": 0,
  "response_format": {
    "type": "json_object"
  },
  "stream": false,
  "temperature": 1,
  "top_p": 1,
  "user": "00000000-0000-0000-0000-000000000000",
  "tools": [
    {
      "type": "function",
      "function": {
        "name": "get_weather",
        "description": "Get the weather for a list of locations",
        "parameters": {
          "type": "object",
          "properties": {
            "locations": {
              "type": "array",
              "items": {
                "type": "string"
              },
              "description": "A list of locations (e.g., city names or zip codes)"
            },
            "unit": {
              "type": "string",
              "enum": ["celsius", "fahrenheit"]
            },
            "request_heartbeat": {
              "type": "boolean",
              "description": "Request an immediate heartbeat after function execution. Set to 'true' if you want to send a follow-up message or run a follow-up function."
            }
          },
          "required": [
            "locations",
            "request_heartbeat"
          ]
        }
      }
    }
  ],
  "tool_choice": "auto"
}
```

Run the following command:
```
curl $LOCALAI/v1/chat/completions   -H "Content-Type: application/json"  -d @request.json | jq
```

**Have you tested this PR?**
```
{
  "created": 1716270786,
  "object": "chat.completion",
  "id": "8ac19035-0de3-48d8-bdfb-55e066b0e08b",
  "model": "hermes-2-pro-theta-llama3",
  "choices": [
    {
      "index": 0,
      "finish_reason": "tool_calls",
      "message": {
        "role": "assistant",
        "content": null,
        "tool_calls": [
          {
            "index": 0,
            "id": "8ac19035-0de3-48d8-bdfb-55e066b0e08b",
            "type": "function",
            "function": {
              "name": "get_weather",
              "arguments": "{\"locations\":[\"boston\",\"seattle\",\"san francesco\"],\"request_heartbeat\":true,\"unit\":\"fahrenheit\"}"
            }
          }
        ]
      }
    }
  ],
  "usage": {
    "prompt_tokens": 426,
    "completion_tokens": 42,
    "total_tokens": 468
  }
}
```

**Related issues or PRs**
N/A

**Is your PR over 500 lines of code?**
No

**Additional context**
Add any other context or screenshots about the PR here.

### CODE REVIEW

**Comment by lenaxia** [comment]
I believe response_format is okay to hard code because memgpt relies 100% on function calls and no plain text responses, so this shouldn't cause any issues with conversations

**Comment by lenaxia** [comment]
Fixed the build errors around poetry and os.env keyerror. The docker error wasnt clear as it just reported permanent sleep so not sure what that was about.

**Comment by sarahwooders** [comment]
@lenaxia could you please fix the formatting errors? You can run `poetry run black . -l 140`.

**Comment by lenaxia** [comment]
So weird, I ran poetry black last time as well, and it reported no issues.

Here's the output from my last run:

```
ubuntu@terraform:~/workspace/MemGPT(⎈|prod:home)$ poetry run black . -l 140
All done! ✨ 🍰 ✨
187 files left unchanged.
ubuntu@terraform:~/workspace/MemGPT(⎈|prod:home)$ git push origin response-format-json-object
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 2 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 460 bytes | 460.00 KiB/s, done.
Total 5 (delta 4), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
To github.com:lenaxia/MemGPT.git
   add58fc..ea78c0f  response-format-json-object -> response-format-json-object
```

**Review by cpacker — APPROVED** [review]
Unit tests seem to be failing due to separate issue with tests on forks.

Thank you! LGTM

**Pull request merged**
