### PR TITLE
build: Update all actions to use cached poetry builds

### PR DESCRIPTION
**Pull request by robbyt**
**Please describe the purpose of this pull request.**
This change simplifies and aligns all actions to use the same Poetry install method. It also removes some extra Poetry config that is now handled by `packetcoders/action-setup-cache-python-poetry`.

**How to test**
n/a

**Have you tested this PR?**
n/a

**Related issues or PRs**
#845 
#844

**Is your PR over 500 lines of code?**
n/a

**Additional context**
This also contains the changes in #844 and #845 - Those should be merged before this.

### CODE REVIEW

**Comment by sarahwooders** [comment]
@robbyt this looks great, but any idea why the tests are failing? Maybe an issue with running with `poetry shell`?

**Comment by robbyt** [comment]
Thanks for the review @sarahwooders yes, I think you're right- it's failing because of the poetry shell command, I'll need to test more before this is ready for merge.

**Comment by robbyt** [comment]
Just a note, the nightly package publish failed because `checkout@v4` is required. This change updates all checkout calls, and should fix that nightly-publish problem.

re: https://github.com/cpacker/MemGPT/actions/runs/7568756512

@sarahwooders please review when you have a chance

**Review by sarahwooders — APPROVED** [review]
Thanks for making the fixes - this looks good to merge!

**Pull request merged**
