### PR TITLE
Added db load ability

### PR DESCRIPTION
**Pull request by mr-sk**
* Added ability to load .db (as shown in original README)
    * This didn't work because it was being read in as the csv file, not the db
* Added README instructions to load .csv (not shown in original README)

### CODE REVIEW

**Comment by mr-sk** [comment]
@vivi Remerged against latest (the spacing and double quotes). Thanks.

**Comment by vivi** [comment]
Hi @mr-sk, thank you for catching this!

It seems like with your changes, we no longer need https://github.com/cpacker/MemGPT/blob/main/memgpt/main.py#L358-L369 anymore. Could you change your PR to reflect that + test?

**Comment by mr-sk** [comment]
Hello @vivi - So after further reading the code, realized that the main section for adding the db into archival memory is correct, and the issue is that in utils the final else (when not explictily handling the .db extension) was attempting to read the sqlite db "raw", causing it to fail on encoding issues. Now, we just return for that file extension, and main handles loading it correctly. 

So this is actually less code and fixes the issue very simply. 

Tested on the local sql .db provided, works well. 
Thanks!

**Comment by cpacker** [comment]
@vivi can this be closed?

**Comment by mr-sk** [comment]
If you close w/out merging you'll get an error when trying to import a db.

**Pull request merged**
