### PR TITLE
fix: remove server locking on agents 

### PR DESCRIPTION
**Pull request by sarahwooders**
**Please describe the purpose of this pull request.**
Locks on the server class are causing strange issues, so removing it for now. Locks should eventually be moved into the `Agent` class (or we should use queues instead). 

**How to test**
`pytest -s tests/test_concurrent_connections.py`

**Have you tested this PR?**
Yes 

**Related issues or PRs**
#1438

### CODE REVIEW

**Review by cpacker — APPROVED** [review]

**Comment by Sapessii** [comment]
Hi! unfortunately I still have the same issue

The problem seems to reside inside memgpt/server/agents/message.py @router.post("/agents/{agent_id}/messages
since it's an async function it cannot accept multiple posts to that endpoint.

The branch streaming-memgpt-api seems to work, what is missing for the merge?

Thank you!

**Comment by sarahwooders** [comment]
> Hi! unfortunately I still have the same issue
> 
> The problem seems to reside inside memgpt/server/agents/message.py `@router.post("/agents/{agent_id}/messages` since it's an async function it cannot accept multiple posts to that endpoint.
> 
> The branch streaming-memgpt-api seems to work, what is missing for the merge?
> 
> To reproduce it just launch the server with "memgpt server" and send concurrently 2 post requests (with different user and different agent) If you put a log before: `if request.role == "user" or request.role is None:` You will see that the log is printed once the previous message is processed
> 
> Thank you!

Are you using the latest server on main (i.e. rebuilding the docker container before running compose, or running `memgpt server`)? I had the same issue previous to this fix but after this PR the test `tests/test_concurrent_connections.py` makes sure different user/agent requests can be concurrently processed.

**Comment by luninaries** [comment]
> > Hi! unfortunately I still have the same issue
> > The problem seems to reside inside memgpt/server/agents/message.py `@router.post("/agents/{agent_id}/messages` since it's an async function it cannot accept multiple posts to that endpoint.
> > The branch streaming-memgpt-api seems to work, what is missing for the merge?
> > To reproduce it just launch the server with "memgpt server" and send concurrently 2 post requests (with different user and different agent) If you put a log before: `if request.role == "user" or request.role is None:` You will see that the log is printed once the previous message is processed
> > Thank you!
> 
> Are you using the latest server on main (i.e. rebuilding the docker container before running compose, or running `memgpt server`)? I had the same issue previous to this fix but after this PR the test `tests/test_concurrent_connections.py` makes sure different user/agent requests can be concurrently processed.

Hi! Thank you for your reply, I wrote you on Discord :)

**Comment by Sapessii** [comment]
> > Hi! unfortunately I still have the same issue
> > The problem seems to reside inside memgpt/server/agents/message.py `@router.post("/agents/{agent_id}/messages` since it's an async function it cannot accept multiple posts to that endpoint.
> > The branch streaming-memgpt-api seems to work, what is missing for the merge?
> > To reproduce it just launch the server with "memgpt server" and send concurrently 2 post requests (with different user and different agent) If you put a log before: `if request.role == "user" or request.role is None:` You will see that the log is printed once the previous message is processed
> > Thank you!
> 
> Are you using the latest server on main (i.e. rebuilding the docker container before running compose, or running `memgpt server`)? I had the same issue previous to this fix but after this PR the test `tests/test_concurrent_connections.py` makes sure different user/agent requests can be concurrently processed.

Hi! Thank you for your reply, I wrote you on Discord :)

**Pull request merged**
