### PR TITLE
updating overwrite error

### PR DESCRIPTION
**Pull request by web3wes**
updating error when user attempts to overwrite existing persona, model, or human

### CODE REVIEW

**Comment by web3wes** [comment]
image

**Comment by web3wes** [comment]
image

**Review by sarahwooders — CHANGES_REQUESTED** [review]
This looks great! One minor thing that would be great to add is to check if the flag conflicts with the `agent_config`. So if they pass in `--persona sam`, but `agent_config.persona == "sam"`, then don't fail since they're not trying to override with a new persona.

**Comment by cpacker** [comment]
should be handled in latest versions, feel free to reopen/rebase if not

**Pull request closed without merging**
