### PR TITLE
fix: Turn off all ensure_ascii of json.dumps

### PR DESCRIPTION
**Pull request by ifsheldon**
**Please describe the purpose of this pull request.**
Fix all `ensure_ascii` in all `json.dumps`, including those in commented out code. Before this, LLMs saw encoded non-ascii characters like `\u038` etc.

**How to test**
Test it with capable LLMs like GPT4. The response should no longer be irrelervant.

**Have you tested this PR?**
Yes

**Related issues or PRs**
This is the first step in #799 , but it can enable capable LLMs like GPT4 to converse in multiple languages.

**Is your PR over 500 lines of code?**
No

### CODE REVIEW

**Review by cpacker — CHANGES_REQUESTED** [review]
@ifsheldon could you run black on your files to make sure it passes the formatting integration test?

https://github.com/cpacker/MemGPT/blob/main/CONTRIBUTING.md#check-formatting

Alternatively you can also just add me as a contributor to your fork repo and I can do it for you

**Comment by ifsheldon** [comment]
OK, sorry. I think I turned on "allow edits from reviewer", but I've run black and pushed a new commit.

**Review by cpacker — CHANGES_REQUESTED** [review]
What do you think about pulling the `ensure_ascii` out as a `False` literal into a setting imports from `memgpt/constants.py`?

This should allow us to toggle back this PR easily if there are some unintended regressions.

**Comment by ifsheldon** [comment]
I think it's fine, but yeah, never a bad thing to be conservative when programming Python.

**Review by cpacker — APPROVED** [review]

**Comment by cpacker** [comment]
Thank you for the awesome PR @ifsheldon !

**Comment by tombedor** [comment]
@ifsheldon @cpacker should we also do a corresponding change for `json.loads`, changing them to `strict=False`?

**Comment by tombedor** [comment]
I've got a commit to do that here: https://github.com/cpacker/MemGPT/commit/b2efcac79c61e4a10b2d73fe72e1198a783ce7dc

**Comment by cpacker** [comment]
@tombedor that sounds like a good idea to me, though I'm not entirely sure of any unintended consequences this might have with OSS LLMs or OpenAI API models like gpt-4. Similarly for that commit @tombedor , can you make it pulled from the constants file instead of set to `False`?

**Comment by tombedor** [comment]
Yeah will do. I might be paranoid but I swear there are some json parsing problems that only happen when debug is off... might run with my branch for a few days to see if it actually fixes things

**Comment by cpacker** [comment]
> Yeah will do. I might be paranoid but I swear there are some json parsing problems that only happen when debug is off... might run with my branch for a few days to see if it actually fixes things

SGTM! Can also open a draft PR, and comment further on the draft PR with any results you notice

**Comment by xlbljz** [comment]
I'm using 0.3.17. It seems that there are still some problems with multi languages json parsing.

```python
> Enter your message: So if I said 你好 to you, what should you say.
[A[K
An exception occurred when running agent.step():
Traceback (most recent call last):
  File "C:\Users\idear\miniconda3\envs\dev\Lib\site-packages\memgpt\data_types.py", line 425, in to_google_ai_dict
    function_args = json.loads(function_args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\idear\miniconda3\envs\dev\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\idear\miniconda3\envs\dev\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\idear\miniconda3\envs\dev\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Invalid \escape: line 1 column 55 (char 54)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\idear\miniconda3\envs\dev\Lib\site-packages\memgpt\main.py", line 408, in run_agent_loop
    new_messages, user_message, skip_next_user_input = process_agent_step(user_message, no_verify)
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\idear\miniconda3\envs\dev\Lib\site-packages\memgpt\main.py", line 377, in process_agent_step
    new_messages, heartbeat_request, function_failed, token_warning, tokens_accumulated = memgpt_agent.step(
                                                                                          ^^^^^^^^^^^^^^^^^^
  File "C:\Users\idear\miniconda3\envs\dev\Lib\site-packages\memgpt\agent.py", line 818, in step
    raise e
  File "C:\Users\idear\miniconda3\envs\dev\Lib\site-packages\memgpt\agent.py", line 746, in step
    response = self._get_ai_reply(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\idear\miniconda3\envs\dev\Lib\site-packages\memgpt\agent.py", line 451, in _get_ai_reply
    raise e
  File "C:\Users\idear\miniconda3\envs\dev\Lib\site-packages\memgpt\agent.py", line 426, in _get_ai_reply
    response = create(
               ^^^^^^^
  File "C:\Users\idear\miniconda3\envs\dev\Lib\site-packages\memgpt\llm_api\llm_api_tools.py", line 133, in wrapper
    raise e
  File "C:\Users\idear\miniconda3\envs\dev\Lib\site-packages\memgpt\llm_api\llm_api_tools.py", line 106, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\idear\miniconda3\envs\dev\Lib\site-packages\memgpt\llm_api\llm_api_tools.py", line 268, in create
    contents=[m.to_google_ai_dict() for m in messages],
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\idear\miniconda3\envs\dev\Lib\site-packages\memgpt\llm_api\llm_api_tools.py", line 268, in <listcomp>
    contents=[m.to_google_ai_dict() for m in messages],
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\idear\miniconda3\envs\dev\Lib\site-packages\memgpt\data_types.py", line 427, in to_google_ai_dict
    raise UserWarning(f"Failed to parse JSON function args: {function_args}")
UserWarning: Failed to parse JSON function args: {"message": "\u4f60\u597d means Hello in Chinese? That\'s so cool! Thank you for teaching me."}```

**Pull request merged**
