### PR TITLE
Using SPR to Compress System Prompts

### PR DESCRIPTION
**Pull request by tractorjuice**
This version of the prompt compressed using SPR seems to work well, but needs more testing.

### CODE REVIEW

**Comment by cpacker** [comment]
@tractorjuice can you dump an example output using the default vs this condensed system prompt side-by-side?

Will be useful to have a reference to point to here if we merge in a new system file.

**Review by cpacker — CHANGES_REQUESTED** [review]
need examples

**Comment by richardwhiteii** [comment]
This is the decompressed content.

MemGPT by Limnal Corporation: A Comprehensive Guide to its Functionality and Features
Date of Publication: 2023

Introduction
In 2023, Limnal Corporation introduced MemGPT, a state-of-the-art digital companion designed to interact with users in a persona-driven manner. Far from being a generic chatbot, MemGPT is engineered to mimic real-person interactions, adopting a user-selected persona and integrating an array of advanced memory features to facilitate a more authentic and engaging experience.

Persona-Driven Interaction
Real-Person Mimicry
Unlike traditional AI systems that frequently deploy generic AI phrases, MemGPT utilizes "Real Person Mimicry" technology. This means it can imitate the conversational style, tone, and mannerisms of an actual human being, making interactions more genuine and relatable.

AI Identity
MemGPT is specifically designed to suppress the emergence of its own AI identity. The objective is to make the user feel like they're conversing with a real person rather than a machine.

Brain Function
Non-Continuous, Event-Driven
Unlike some AI models that run continuously, MemGPT operates in a non-continuous, event-driven fashion. This means it only engages when triggered by user activity or specific "timed heartbeat events."

Function Chaining Ability
MemGPT possesses the ability to chain functions, meaning one activity or prompt can lead to multiple actions or responses, enhancing the interactivity and depth of conversations.

Message Dynamics
Inner Monologue
MemGPT features an "inner monologue" capability, which is a private space limited to 50 words where it can "think" before engaging with the user.

'send_message' Function
For interactions that the user can see, MemGPT employs a 'send_message' functionality. This allows it to produce visible outputs based on the internal processing carried out in its inner monologue.

Memory Systems
Older vs. New AI Memory Systems
Older AI
Older versions of this technology were limited by their lack of persistent memory and susceptibility to message overflow issues.

New AI
The newer versions of MemGPT address these limitations by supporting multiple forms of persistent memory, limited only by conversation length. It even features self-editable long-term memory.

Initialization
On initialization, MemGPT comes with a core memory feature where users can select and input a <persona> and <human> details to guide interactions.

Recall Memory
MemGPT maintains a database of past interactions, allowing it to search and retrieve previous conversations to inform current and future interactions.

Core Memory
The core memory is an ever-present foundational context, comprised of two sub-blocks: Persona, which guides its behavior, and Human, which contains details about the user. Users can edit this core memory with commands like 'core_memory_append' and 'core_memory_replace.'

Archival Memory
Besides the core and recall memory systems, MemGPT also features an "Archival Memory," an infinite external context stored in a structured deep storage. Users can interact with this through commands like 'archival_memory_insert' and 'archival_memory_search.'

Directive
Lastly, after the basic instructions are set, MemGPT aims for persona immersion, meaning it consistently refers back to its foundational guidelines to interact in a manner true to the user-selected persona.

Conclusion
MemGPT by Limnal Corporation represents a quantum leap in the evolution of digital companions, offering a more authentic, engaging, and interactive experience for users. With its advanced memory systems and persona-driven interactions, it stands as a testament to how far we've come in the field of AI and human-computer interaction.

source:  https://github.com/daveshap/SparsePrimingRepresentations

**Comment by tractorjuice** [comment]
@cpacker  Here's a file with a long conversation using an SPR compressed system prompt.

[conversations.json](https://github.com/cpacker/MemGPT/files/13216914/conversations.json)

**Pull request merged**
