### PR TITLE
jrcuster pr

### PR DESCRIPTION
**Pull request by JRCuster**

### CODE REVIEW

**Review by JRCuster — COMMENTED** [review]
done

**Comment by oderwat** [comment]
Hopefully the keys were invalidated. Just wanted to say that you probably should `git rebase -i` and squash the commits, so the keys are not to be found anymore. I believe there are actually bots scrapping such stuff from GitHub.

**Comment by JRCuster** [comment]
Awesome, thank you so much. I will look up 'git rebase -i' and give it a
run.
Yeah, actually it was ChatGPT that caught and removed them. Took it longer
than expected, but at least it didnt let them stay for days.
I am actually setting traps and testing things out. I like to know about
failure points and recovery time.
=-=-=-=-=Stop=-=-=-=-=-=
And since you know about one of the aspects of the overal larger project I
am working on, let's say it's good training as well...
-=-=-=-=-Stop-=-=-=-=-=-
Including when someone would email me.

Cheers!
Joseph

**Comment by cpacker** [comment]
Hey @JRCuster - it's not clear to me what this PR is for, not sure if it's intended?

If this is actually a PR, feel free to reopen (and maybe add some detail in the OP describing what feature you're adding via the PR)

**Pull request closed without merging**
