### PR TITLE
Chroma storage integration 

### PR DESCRIPTION
**Pull request by sarahwooders**
Depends on #226

To-dos: 

- [x] Rebase on `main`
- [x] Add dependencies via poetry, with optional dependency `chroma`
- [x] Updates tests for `tests/test_local_archival.py` and `tests/test_storage.py`
- [x] Add chroma option to `memgpt configure`
- [x] Add installation/setup instructions in docs 
- [x] Implement paginated get (e.g. https://github.com/cpacker/MemGPT/blob/main/memgpt/connectors/db.py#L80)

### CODE REVIEW

**Comment by jeffchuber** [comment]
would love to see this! 🎉

**Review by cpacker — APPROVED** [review]
SGTM assuming the chroma test runs and passes (not a skip via openai key missing issue)

**Comment by jeffchuber** [comment]
would you all be interested in adding an integrations page to https://docs.trychroma.com/integrations to help discoverability?

**Comment by cpacker** [comment]
@jeffchuber definitely! I added some basic notes here: https://github.com/chroma-core/docs/pull/184

Let me know if there's anything else you think I should add (feel free to edit directly).

**Pull request merged**
