### PR TITLE
legacy-cli: Allow generating embeddings off openAI when using local LLM

### PR DESCRIPTION
**Pull request by vivi**
This is a patch while we work out the bugs in the local LLM workflow on the new CLI.

Addresses part of #138

### CODE REVIEW

**Review by cpacker — CHANGES_REQUESTED** [review]
Errors out if you unset `OPENAI_API_KEY`:

```
Press ENTER to continue...

Unhandled exception in event loop:
  File "/Users/loaner/dev/MemGPT-public/MemGPT/memgpt/utils.py", line 245, in bounded_process_chunk
    return await process_chunk(i, chunk, model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/loaner/dev/MemGPT-public/MemGPT/memgpt/utils.py", line 236, in process_chunk
    raise e
  File "/Users/loaner/dev/MemGPT-public/MemGPT/memgpt/utils.py", line 233, in process_chunk
    return i, await async_get_embedding_with_backoff(chunk["content"], model=model)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/loaner/dev/MemGPT-public/MemGPT/memgpt/openai_tools.py", line 158, in async_get_embedding_with_backoff
    response = await acreate_embedding_with_backoff(input=[text], model=model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/loaner/dev/MemGPT-public/MemGPT/memgpt/openai_tools.py", line 115, in wrapper
    raise e
  File "/Users/loaner/dev/MemGPT-public/MemGPT/memgpt/openai_tools.py", line 95, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/loaner/dev/MemGPT-public/MemGPT/memgpt/openai_tools.py", line 151, in acreate_embedding_with_backoff
    return await openai.Embedding.acreate(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/openai/api_resources/embedding.py", line 73, in acreate
    response = await super().acreate(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 216, in acreate
    ) = cls.__prepare_create_request(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 108, in __prepare_create_request
    requestor = api_requestor.APIRequestor(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/openai/api_requestor.py", line 139, in __init__
    self.api_key = key or util.default_api_key()
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/openai/util.py", line 186, in default_api_key
    raise openai.error.AuthenticationError(

Exception No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.
```

**Comment by sarahwooders** [comment]
For the new CLI, you just modify `memgpt config` and  `embedding.py`, you can separate out the embedding model and main model config. I can do it tomorrow if it's an issue.

**Review by cpacker — COMMENTED** [review]
Do these changes warrant any updates to the readthedocs?

eg https://memgpt.readthedocs.io/en/latest/endpoints/

**Comment by vivi** [comment]
> Do these changes warrant any updates to the readthedocs?
> 
> eg https://memgpt.readthedocs.io/en/latest/endpoints/

No, given that the readthedocs don't contain anything about the legacy cli atm.

**Pull request closed without merging**
